### ISSUE TITLE
ALTER ATTACK

### ISSUE THREAD

**Issue by Dastgsm** [aluminiumi/srsLTE-plus-sib12#1]
Hey have you any idea for doing alter attack.

It's will be helpfull also,

**Comment by aluminiumi** [comment]
This project was an academic assignment with the goal of adding capability to srsLTE to send SIB12 messages. The aLTEr attack does not use SIB12 messages (to my knowledge) and is outside the scope of this project.

**Comment by Dastgsm** [comment]
what kind of phone do you use for the testing of SIB12?

    Le lundi 1 juin 2020 à 00:44:33 UTC+4, aluminiumi <notifications@github.com> a écrit :  
 
 


Closed #1.
